#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

POSTGRES_USER="${POSTGRES_USER:-postgres}"
UNMS_POSTGRES_DB="${UNMS_POSTGRES_DB:-unms}"
UNMS_POSTGRES_SCHEMA="${UNMS_POSTGRES_SCHEMA:-unms}"
UNMS_POSTGRES_USER="${UNMS_POSTGRES_USER:-unms}"
UNMS_POSTGRES_PASSWORD="${UNMS_POSTGRES_PASSWORD:-unms}"
UCRM_POSTGRES_SCHEMA="${UCRM_POSTGRES_SCHEMA:-ucrm}"
UCRM_POSTGRES_USER="${UCRM_POSTGRES_USER:-ucrm}"
UCRM_POSTGRES_PASSWORD="${UCRM_POSTGRES_PASSWORD:-ucrm}"

DATABASE="${UNMS_POSTGRES_DB}"

# Create single database.
psql --variable ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --command "CREATE DATABASE ${DATABASE}"

# Create unms user.
psql --variable ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --command "CREATE USER ${UNMS_POSTGRES_USER} SUPERUSER PASSWORD '${UNMS_POSTGRES_PASSWORD}'"
psql --variable ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --command "GRANT ALL PRIVILEGES ON DATABASE ${DATABASE} TO ${UNMS_POSTGRES_USER}"
psql --variable ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${DATABASE}" --command "CREATE SCHEMA ${UNMS_POSTGRES_SCHEMA} AUTHORIZATION ${UNMS_POSTGRES_USER}"
psql --variable ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --command "ALTER USER ${UNMS_POSTGRES_USER} SET search_path = ${UNMS_POSTGRES_SCHEMA},public"

# Create ucrm user.
psql --variable ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --command "CREATE USER ${UCRM_POSTGRES_USER} SUPERUSER PASSWORD '${UCRM_POSTGRES_PASSWORD}'"
psql --variable ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --command "GRANT ALL PRIVILEGES ON DATABASE ${DATABASE} TO ${UCRM_POSTGRES_USER}"
psql --variable ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${DATABASE}" --command "CREATE SCHEMA ${UCRM_POSTGRES_SCHEMA} AUTHORIZATION ${UCRM_POSTGRES_USER}"
psql --variable ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --command "ALTER USER ${UCRM_POSTGRES_USER} SET search_path = ${UCRM_POSTGRES_SCHEMA},public"
